name: Test deploy 1
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build:test --if-present
    - name: Deploy to Server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
          DEPLOY_KEY: ${{ secrets.SSH_PEM_KEY }}
          ARGS: ""
          FOLDER: "dist/test/"
          SERVER_IP: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          SERVER_PORT: ${{ secrets.REMOTE_PORT }} 
          SERVER_DESTINATION: ${{ secrets.SERVER_TEST_FOLDER }}
